/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Commands.CommandManager;
import Commands.Mul;
import Commands.Set;
import Commands.UndoableCommand;
import Model.Model;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author givelpa
 */
public class AppliMVC extends javax.swing.JFrame {

    private Model model;
    private CommandManager commandManager = new CommandManager();

    /**
     * Creates new form AppliMVC
     */
    public AppliMVC() {
        initComponents();
        setModel(new Model());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSetters = new javax.swing.JPanel();
        buttonSet10 = new javax.swing.JButton();
        buttonSet20 = new javax.swing.JButton();
        buttonSet30 = new javax.swing.JButton();
        panelCommands = new javax.swing.JPanel();
        buttonMul2 = new javax.swing.JButton();
        buttonMul3 = new javax.swing.JButton();
        buttonDiv2 = new javax.swing.JButton();
        buttonDiv3 = new javax.swing.JButton();
        panelView = new javax.swing.JPanel();
        labelValue = new javax.swing.JLabel();
        textFieldValue = new javax.swing.JTextField();
        labelMean = new javax.swing.JLabel();
        textFieldMean = new javax.swing.JTextField();
        labelNbOfChanges = new javax.swing.JLabel();
        textFieldNbOfChanges = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        buttonSet10.setText("10");
        buttonSet10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSet10ActionPerformed(evt);
            }
        });
        panelSetters.add(buttonSet10);

        buttonSet20.setText("20");
        buttonSet20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSet20ActionPerformed(evt);
            }
        });
        panelSetters.add(buttonSet20);

        buttonSet30.setText("30");
        buttonSet30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSet30ActionPerformed(evt);
            }
        });
        panelSetters.add(buttonSet30);

        getContentPane().add(panelSetters);

        buttonMul2.setText("x2");
        buttonMul2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMul2ActionPerformed(evt);
            }
        });
        panelCommands.add(buttonMul2);

        buttonMul3.setText("x3");
        buttonMul3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMul3ActionPerformed(evt);
            }
        });
        panelCommands.add(buttonMul3);

        buttonDiv2.setText("/2");
        buttonDiv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDiv2ActionPerformed(evt);
            }
        });
        panelCommands.add(buttonDiv2);

        buttonDiv3.setText("/3");
        buttonDiv3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDiv3ActionPerformed(evt);
            }
        });
        panelCommands.add(buttonDiv3);

        getContentPane().add(panelCommands);

        panelView.setLayout(new java.awt.GridLayout(3, 2));

        labelValue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelValue.setText("Value :");
        panelView.add(labelValue);

        textFieldValue.setPreferredSize(new java.awt.Dimension(100, 30));
        panelView.add(textFieldValue);

        labelMean.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelMean.setText("Mean :");
        panelView.add(labelMean);

        textFieldMean.setPreferredSize(new java.awt.Dimension(100, 30));
        panelView.add(textFieldMean);

        labelNbOfChanges.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelNbOfChanges.setText("Number of changes :");
        panelView.add(labelNbOfChanges);

        textFieldNbOfChanges.setPreferredSize(new java.awt.Dimension(100, 30));
        panelView.add(textFieldNbOfChanges);

        getContentPane().add(panelView);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSet10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSet10ActionPerformed
        commandManager.registerCommand(new Set(model, 10));
    }//GEN-LAST:event_buttonSet10ActionPerformed

    private void buttonSet20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSet20ActionPerformed
        commandManager.registerCommand(new Set(model, 20));
    }//GEN-LAST:event_buttonSet20ActionPerformed

    private void buttonSet30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSet30ActionPerformed
        commandManager.registerCommand(new Set(model, 30));
    }//GEN-LAST:event_buttonSet30ActionPerformed

    private void buttonMul2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMul2ActionPerformed
        commandManager.registerCommand(new Mul(model, 2));
    }//GEN-LAST:event_buttonMul2ActionPerformed

    private void buttonMul3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMul3ActionPerformed
        commandManager.registerCommand(new Mul(model, 3));
    }//GEN-LAST:event_buttonMul3ActionPerformed

    private void buttonDiv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDiv2ActionPerformed
        commandManager.registerCommand(new Mul(model, 1.0/2.0));
    }//GEN-LAST:event_buttonDiv2ActionPerformed

    private void buttonDiv3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDiv3ActionPerformed
        commandManager.registerCommand(new Mul(model, 1.0/3.0));
    }//GEN-LAST:event_buttonDiv3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDiv2;
    private javax.swing.JButton buttonDiv3;
    private javax.swing.JButton buttonMul2;
    private javax.swing.JButton buttonMul3;
    private javax.swing.JButton buttonSet10;
    private javax.swing.JButton buttonSet20;
    private javax.swing.JButton buttonSet30;
    private javax.swing.JLabel labelMean;
    private javax.swing.JLabel labelNbOfChanges;
    private javax.swing.JLabel labelValue;
    private javax.swing.JPanel panelCommands;
    private javax.swing.JPanel panelSetters;
    private javax.swing.JPanel panelView;
    private javax.swing.JTextField textFieldMean;
    private javax.swing.JTextField textFieldNbOfChanges;
    private javax.swing.JTextField textFieldValue;
    // End of variables declaration//GEN-END:variables

    public void setModel(Model model) {
        this.model = model;
        
        textFieldValue.setText(""+model.getValue());
        textFieldMean.setText(""+model.getMean());
        textFieldNbOfChanges.setText(""+model.getNbChanges());
        
        model.addPropertyChangeListener(model.PROPERTY_VALUE, (evt) -> {
            textFieldValue.setText(""+model.getValue());
        });
        model.addPropertyChangeListener(model.PROPERTY_MEAN, (evt) -> {
            textFieldMean.setText(""+model.getMean());
        });
        model.addPropertyChangeListener(model.PROPERTY_NBCHANGES, (evt) -> {
            textFieldNbOfChanges.setText(""+model.getNbChanges());
        });
    }
    
    public Model getModel(){
        return this.model;
    }
}
